apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-dcgm
  namespace: gpu-operator
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-dcgm
  namespace: gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-dcgm
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
